#ifndef keyapPPC2100_1505_h_
#define keyapPPC2100_1505_h_

#define S$KEYMATRIX_MAXCOUNT    400

#define OFFSET_EX2_01            216

/*  0 -- 9 PPC2100  Left Key */
#define S$KEYMATRIX_CUTTER_FW		0
#define S$KEYMATRIX_EXTRUDER_UP		1
#define S$KEYMATRIX_CARRIAGE_UP		2
#define S$KEYMATRIX_CARRIAGE_DN		3
#define S$KEYMATRIX_CLAMP_CLS		4
#define S$KEYMATRIX_CLAMP_OPN		5
#define S$KEYMATRIX_BLOWPIN_DN		6
#define S$KEYMATRIX_BLOWPIN_UP		7
#define S$KEYMATRIX_BLOW			8
#define S$KEYMATRIX_HOOK_PIN_FW 	9
/* 10 -- 21 PPC2100 Middle Key */


#define S$KEYMATRIX_TOP_DEFLASH_FW	10
#define S$KEYMATRIX_TOP_DEFLASH_BW	11
#define S$KEYMATRIX_ROBOT_FW		12
#define S$KEYMATRIX_ROBOT_CLS		13
#define S$KEYMATRIX_COOL_DN			14
#define S$KEYMATRIX_COOL_BLOW		15
#define S$KEYMATRIX_COOL2_DN		16
#define S$KEYMATRIX_COOL2_BLOW		17
#define S$KEYMATRIX_COOL3_DN		18
#define S$KEYMATRIX_COOL3_BLOW		19
#define S$KEYMATRIX_SUBMOLD_OPN		20
#define S$KEYMATRIX_SUBMOLD_CLS		21

//#define S$KEYMATRIX_BLOW			12
//#define S$KEYMATRIX_PRODUCTAUX_CLS	13
//#define S$KEYMATRIX_ROBOT_FWBW		14
//#define S$KEYMATRIX_ROBOT_CLS		15



/* 22 -- 31 PPC2100 Right Key */

#define S$KEYMATRIX_HEAT_POWER		22
//#define S$KEYMATRIX_EXTRUDER_A_PLK	23
//#define S$KEYMATRIX_EXTRUDER_B_PLK	24
//#define S$KEYMATRIX_EXTRUDER_C_PLK	25

/*for ABB inveter ------------------------------*/
#define S$KEYMATRIX_EXTRUDER_A_ABB	23
#define S$KEYMATRIX_EXTRUDER_D_ABB	24
#define S$KEYMATRIX_EXTRUDER_B_ABB	25
#define S$KEYMATRIX_EXTRUDER_C_ABB	26
#define S$KEYMATRIX_EXTRUDER_V_ABB	153 //Follow Extruder_D
/*-----------------------------------------------*/
//#define S$KEYMATRIX_EXTRUDER_V_ABB	26

#define S$KEYMATRIX_PARISON_PUMP	100

#define S$KEYMATRIX_MAIN_PUMP		27
#define S$KEYMATRIX_MODE_MANUAL		28
#define S$KEYMATRIX_MODE_AUTO		29
#define S$KEYMATRIX_AUTO_STOP		30
#define S$KEYMATRIX_MODE_CALIB		31


/*200 -- 215 Visual Funcion Key*/

#define S$KEYMATRIX_F1   				200
#define S$KEYMATRIX_F2   				201
#define S$KEYMATRIX_F3   				202
#define S$KEYMATRIX_F4   				203
#define S$KEYMATRIX_F5   				204
#define S$KEYMATRIX_F6   				205
#define S$KEYMATRIX_F7   				206
#define S$KEYMATRIX_F8   				207
#define S$KEYMATRIX_F9   				208
#define S$KEYMATRIX_F10   				209
#define S$KEYMATRIX_F11   				210
#define S$KEYMATRIX_F12   				211
#define S$KEYMATRIX_F13   				212
#define S$KEYMATRIX_F14   				213
#define S$KEYMATRIX_F15   				214
#define S$KEYMATRIX_F16   				215

/*Auto Reset*/

#define S$KEYMATRIX_AUTO_RESET			100

/* reserve key  */

#define S$KEYMATRIX_NUM7   		 	60
#define S$KEYMATRIX_NUM8   		 	61
#define S$KEYMATRIX_NUM9   		 	62
#define S$KEYMATRIX_NUM4   		 	64
#define S$KEYMATRIX_NUM5   		 	65
#define S$KEYMATRIX_NUM6   		 	66
#define S$KEYMATRIX_NUM1   		 	68	
#define S$KEYMATRIX_NUM2   			69
#define S$KEYMATRIX_NUM3   		 	70
#define S$KEYMATRIX_NUM0   		 	73

#define S$KEYMATRIX_ESC    		 	63
#define S$KEYMATRIX_DEL			 	67
#define S$KEYMATRIX_ENTER  	     	71
#define S$KEYMATRIX_TAB          	77
#define S$KEYMATRIX_UP				75
#define S$KEYMATRIX_DOWN			79
#define S$KEYMATRIX_LEFT			76
#define S$KEYMATRIX_RIGHT			78





//#define S$KEYMATRIX_TOP_DEFLASH_BW  101
//#define S$KEYMATRIX_ROBOT_FW   		102
#define S$KEYMATRIX_ROBOT_BW   		103
#define S$KEYMATRIX_ROBOT_OPN    	104
//#define S$KEYMATRIX_ROBOT_CLS 		105
#define S$KEYMATRIX_SUPPORT   		106
#define S$KEYMATRIX_SPEED_UP   		107
#define S$KEYMATRIX_SPEED_DN   	    108
#define S$KEYMATRIX_COOL_DEFLASH    109
#define S$KEYMATRIX_BLOW_LOW        110

#define S$KEYMATRIX_SERVO_VALVE   	113
#define S$KEYMATRIX_AUTO_LUB   		114
#define S$KEYMATRIX_DIEGAP_UP      	115
#define S$KEYMATRIX_DIEGAP_DN  	    116
#define S$KEYMATRIX_FEED_OPEN       117
//#define S$KEYMATRIX_VISU_EXTRUDER	118
#define S$KEYMATRIX_CUT_NECK		119

//#define S$KEYMATRIX_COOL_DN		111
//#define S$KEYMATRIX_COOL_BLOW		112
//#define S$KEYMATRIX_COOL2_DN		133
//#define S$KEYMATRIX_COOL2_BLOW	134
//#define S$KEYMATRIX_COOL3_DN		120
//#define S$KEYMATRIX_COOL3_BLOW	121
#define S$PAGE_FAST_SEETING			122

#define S$KEYMATRIX_PULL_BOTTOM_FW  123
#define S$KEYMATRIX_PIN_PART_FW  	124
#define S$KEYMATRIX_PIN_PART_BW	   	125
#define S$KEYMATRIX_HANDLE_PUNCHER  126
//#define S$KEYMATRIX_HOOK_PIN_FW   127
//#define S$KEYMATRIX_EXTRUDER_UP	128
#define S$KEYMATRIX_EXTRUDER_DN		129
#define S$KEYMATRIX_SCREW_FW	    131
#define S$KEYMATRIX_SCREW_BW  	    132
#define S$PAGE_FAST_SEETING 		134
#define S$KEYMATRIX_BLOWPINDN_HOLD	135
#define S$KEYMATRIX_BOTSUBMOLD_OPN	136
#define S$KEYMATRIX_VACCUM  	    137
#define S$KEYMATRIX_BOTSUBMOLD_CLS  138
#define S$KEYMATRIX_MINOR_PUMP      139
#define S$KEYMATRIX_PENU_VALVE      140 
#define S$KEYMATRIX_COOLING_PUMP   	141
#define S$KEYMATRIX_SENSOR_UP       142
#define S$KEYMATRIX_SENSOR_DN       143
#define S$KEYMATRIX_SENSOR_BOTTLE   144
#define S$KEYMATRIX_HOPPER_A   	    145
#define S$KEYMATRIX_DRY_CYCLE    	147

#define S$KEYMATRIX_BOT_DEFLASH_FW   	148
#define S$KEYMATRIX_BOT_DEFLASH_BW   	149
//#define S$KEYMATRIX_SUBMOLD_OPN   	150
//#define S$KEYMATRIX_SUBMOLD_CLS 		151

#define S$KEYMATRIX_LUBRICATION     152


#define S$KEYMATRIX_EXTRUDER_A		154
#define S$KEYMATRIX_EXTRUDER_B		155
#define S$KEYMATRIX_EXTRUDER_C		156
#define S$KEYMATRIX_VISU_EXTRUDER	157
#define S$KEYMATRIX_VISU_EXTRUDER_PLK	158
#define S$KEYMATRIX_ALARM_RESET		159
//#define S$PAGE_FAST_SEETING			160

#define S$KEYMATRIX_PLATE_UP		161
#define S$KEYMATRIX_PLATE_DN		162
#define S$KEYMATRIX_PLATE_FW		163
#define S$KEYMATRIX_PLATE_BW		164



#endif


